Fixed exception raised when using maxDataPoints.
When requesting to limit the number of points returned by
the ``/render`` resource, the following exception is raised:

    TypeError: slice indices must be integers or None or have an __index__ method

This is due because math.ceil returns a float value but
the remaining of ``prune_datapoints`` function expects to deal
with integers.